### ISSUE TITLE
 Hyper 2 Weird Transparency

### ISSUE THREAD

**Issue by pokono** [licatajustin/hyper-sierra-vibrancy#1]
Using Hyper 2, the transparency changed completely.
I don't know what is causing this or what the solution may be. Any advice?

<img width="1246" alt="screen shot 2018-04-17 at 2 20 01 pm" src="https://user-images.githubusercontent.com/358137/38888741-91857b92-424a-11e8-8212-f216715aadf8.png">

**Comment by licatajustin** [comment]
What is the exact version of Hyper that you are using?

**Comment by pokono** [comment]
<img width="532" alt="screen shot 2018-04-17 at 2 29 10 pm" src="https://user-images.githubusercontent.com/358137/38889129-b5362aea-424b-11e8-82df-a19b21d2fe39.png">

**Comment by pokono** [comment]
This is all I have installed! Thanks for looking into it.

**Comment by licatajustin** [comment]
Cool -- I'll check it out. If you have any interest in diving into it, I'd gladly welcome a contribution 😄

**Comment by pokono** [comment]
@licatajustin I'll take a look as well! If I understand how everything works I'll send a PR your way!

**Comment by pokono** [comment]
@licatajustin submitted PR #2.

**Comment by licatajustin** [comment]
Fixed with https://github.com/licatajustin/hyper-sierra-vibrancy/pull/2.
